version: '3'
services:
  amocrm-integration:
    image: spiratio/amocrm-integration:1.0.3
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL={MONGO_URL}
      - CLIENT_SECRET={CLIENT_SECRET}
      - CLIENT_ID={CLIENT_ID}
      - SERVER_URL={SERVER_URL}
      - PORT=3000